name: Kita-dake Sanso Checker

on:
  schedule:
    - cron: "0 * * * *"  # UTC毎時00分に実行（日本時間 +9h）
  workflow_dispatch:

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install requests
      - name: Run checker
        env:
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          MASTER_NO: ${{ secrets.MASTER_NO }}
          SERVICE_TYPE1_ID: ${{ secrets.SERVICE_TYPE1_ID }}
          SERVICE_TYPE2_ID: ${{ secrets.SERVICE_TYPE2_ID }}
          TARGET_DATE: ${{ secrets.TARGET_DATE }}
        run: python check.py
